#:schema node_modules/wrangler/config-schema.json

name = "artify"
compatibility_date = "2025-03-28"
compatibility_flags = ["nodejs_compat"]

# Output directory for Cloudflare Pages build
pages_build_output_dir = "./build/client"

# Don't send usage metrics
send_metrics = false

[build]
command = "pnpm build"

[env.production]
vars = { NODE_ENV = "production" }

[vars]
CLERK_PUBLISHABLE_KEY = "pk_test_YmFsYW5jZWQtYmFzaWxpc2stNy5jbGVyay5hY2NvdW50cy5kZXYk"
CLERK_SECRET_KEY = "sk_test_GVWNnq85WBQORoNGKn5wxR2tFEUmxVEptzNi9Tu8DP"
